import type {
  ImageGenerator,
  ImageGenerateParams,
  GenerateResult,
  ProviderConfig,
} from "../types";
import { withRetry } from "@/lib/retry";

export class GeminiImageGenerator implements ImageGenerator {
  private apiKey: string;
  private defaultModel: string;
  private baseUrl: string;

  constructor(config: ProviderConfig) {
    this.apiKey = config.apiKey;
    this.defaultModel = config.model || "gemini-2.0-flash-exp";
    this.baseUrl = config.baseUrl || "https://generativelanguage.googleapis.com";
  }

  private isImagenModel(model: string): boolean {
    return model.startsWith("imagen");
  }

  async generate(params: ImageGenerateParams): Promise<GenerateResult> {
    const model = params.model || this.defaultModel;

    if (this.isImagenModel(model)) {
      return this.generateWithImagen(model, params);
    }
    return this.generateWithGemini(model, params);
  }

  /** Imagen models use the :predict endpoint */
  private async generateWithImagen(
    model: string,
    params: ImageGenerateParams
  ): Promise<GenerateResult> {
    return withRetry(async () => {
      const response = await fetch(
        `${this.baseUrl}/v1beta/models/${model}:predict`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "x-goog-api-key": this.apiKey,
          },
          body: JSON.stringify({
            instances: [{ prompt: params.prompt }],
            parameters: {
              sampleCount: 1,
              aspectRatio: "16:9",
              personGeneration: "allow_all",
            },
          }),
        }
      );

      if (!response.ok) {
        const status = response.status;
        const error = await response.text();
        const err = new Error(`Imagen generation failed (${status}): ${error}`);
        (err as unknown as Record<string, unknown>).status = status;
        throw err;
      }

      const data = await response.json();
      const prediction = data.predictions?.[0];

      if (!prediction?.bytesBase64Encoded) {
        throw new Error("No image generated by Imagen");
      }

      return {
        base64: prediction.bytesBase64Encoded,
      };
    }, { label: `imagen:${model}` });
  }

  /** Gemini models use the :generateContent endpoint */
  private async generateWithGemini(
    model: string,
    params: ImageGenerateParams
  ): Promise<GenerateResult> {
    return withRetry(async () => {
      const response = await fetch(
        `${this.baseUrl}/v1beta/models/${model}:generateContent?key=${this.apiKey}`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            contents: [
              {
                parts: [{ text: params.prompt }],
              },
            ],
            generationConfig: {
              responseModalities: ["IMAGE", "TEXT"],
              responseMimeType: "image/png",
            },
          }),
        }
      );

      if (!response.ok) {
        const status = response.status;
        const error = await response.text();
        const err = new Error(`Gemini image generation failed (${status}): ${error}`);
        (err as unknown as Record<string, unknown>).status = status;
        throw err;
      }

      const data = await response.json();
      const imagePart = data.candidates?.[0]?.content?.parts?.find(
        (p: { inlineData?: unknown }) => p.inlineData
      );

      if (!imagePart?.inlineData?.data) {
        throw new Error("No image generated by Gemini");
      }

      return {
        base64: imagePart.inlineData.data,
      };
    }, { label: `gemini-image:${model}` });
  }
}
